#!/bin/bash

while [[ $# -gt 0 ]]; do
    case "$1" in
        -L)
            LICENSE=true
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
    shift
done

echo "This script will create a new GitHub repository in the current directory."
read -p "Are you sure you want to proceed? (y/n): " response

if [ "$response" == "y" ] || [ "$response" == "Y" ]; then
    echo "Creating a new repository..."
else
    echo "Canceled."
    exit 0
fi

reponame=$(basename "$(pwd)")

# Create the repository
repo_info=$(gh repo create "$reponame" --public)

username_repo="${repo_info#*repository }"
username_repo="${username_repo%% on*}"

if [ -z "$username_repo" ]; then
    echo "Repository creation failed. Please check if 'gh' (GitHub CLI) is installed and configured."
    exit 1
fi

if [ "$LICENSE" = true ]; then
    curl -fL -o "LICENSE" --silent "https://raw.githubusercontent.com/teamdigitale/licenses/master/AGPL-3.0-or-later"
fi

# Initialize and push to the repository
git init --quiet
git add .
git commit -m "Initial commit" --quiet
git remote add origin $username_repo
git push -u origin master --quiet

# Open the repository in the default web browser
gh repo view --web
